### ISSUE TITLE
py setup test causes gdbm related error

### ISSUE THREAD

**Issue by shoemakerlevy9** [RoverRobotics/openrover-python#2]
This occurred on both my laptop and the raspberry pi, both of which have ubuntu 16.04 installed and I had to manually upgrade python3 using [this tutorial](http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/)

```
ubuntu@roverrobotics:~$ py setup test
Traceback (most recent call last):
  File "/usr/lib/python3.6/dbm/gnu.py", line 4, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 7, in <module>
    import dbm.gnu as gdbm
  File "/usr/lib/python3.6/dbm/gnu.py", line 6, in <module>
    raise ImportError(str(msg) + ', please install the python3-gdbm package')
ImportError: No module named '_gdbm', please install the python3-gdbm package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
  File "/usr/lib/python3/dist-packages/CommandNotFound/__init__.py", line 3, in <module>
    from CommandNotFound.CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 9, in <module>
    import gdbm
ModuleNotFoundError: No module named 'gdbm'
```

**Comment by rotu** [comment]
Closing this as user error. I have no idea why it was searching for gdbm, and the correct way to install this package is with `pip`. Also, the command `py setup test` is looking for a file named `setup` where the setup file is `setup.py`
